org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Tipo di estensione: music, tracker o lyrics
extType=music
extId=khinsider
extClass=KhinsiderExtension
extIconUrl=
extName=Khinsider
extDescription=Colonne sonore di videogiochi da khinsider (mirror squid.wtf)
extAuthor=zippatias
extAuthorUrl=
extRepoUrl=https://github.com/zippatias/echo-khinsider-extension
extUpdateUrl=https://api.github.com/repos/zippatias/echo-khinsider-extension/releases
