org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Tipo di estensione: music, tracker o lyrics
extType=music
extId=khinsider
extClass=KHInsiderExtension
extIconUrl=https://raw.githubusercontent.com/zippatias/echo-khinsider-extension/main/icon.png
extName=KHInsider
extDescription=Colonne sonore di videogiochi da KHInsider (mirror squid.wtf)
extAuthor=zippatias
extAuthorUrl=https://github.com/zippatias
extRepoUrl=https://github.com/zippatias/echo-khinsider-extension
extUpdateUrl=https://api.github.com/repos/zippatias/echo-khinsider-extension/releases
